//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jellow2._0.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Experience { get; set; }
        public decimal Salary { get; set; }
        public System.DateTime StartDate { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> FreelancerID { get; set; }
        public Skill SkillRequirement { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Freelancer Freelancer { get; set; }
    }
}
