//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jellow2._0.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Experience { get; set; }
        public decimal Budget { get; set; }
        public string DueDate { get; set; }
        public Nullable<int> ConsumerID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> FreelancerID { get; set; }
        public Skill SkillRequirement { get; set; }
    
        public virtual Consumer Consumer { get; set; }
        public virtual Company Company { get; set; }
        public virtual Freelancer Freelancer { get; set; }
    }
}
