//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jellow2._0.Database
{
    using System;
    
    public enum Skill : short
    {
        Java = 1,
        DevOps = 2,
        CSharp = 3,
        FrontEnd = 4,
        SQL = 5,
        FullStack = 6
    }
}
